version: '3.4'

services:
  backtdpii:
    image: backtdpii
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: back-tdp-ii:*
      DATABASE_URL: mongodb://mongodb:27017/test
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  
volumes: 
  data: